# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iOScheckLagConfig_old.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_iOSInternationalTest(QDialog):

    # mySignal = pyqtSignal(dict)
    def setupUi(self, iOSInternationalTest):
        iOSInternationalTest.setObjectName("iOSInternationalTest")
        iOSInternationalTest.resize(632, 439)
        self.label = QtWidgets.QLabel(iOSInternationalTest)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(iOSInternationalTest)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 170, 581, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 4, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 2, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 3, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 5, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(iOSInternationalTest)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 50, 581, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(iOSInternationalTest)
        self.label_4.setGeometry(QtCore.QRect(10, 145, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.but_sure = QtWidgets.QPushButton(iOSInternationalTest)
        self.but_sure.setGeometry(QtCore.QRect(60, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.but_sure.setFont(font)
        self.but_sure.setObjectName("but_sure")
        self.but_cancel = QtWidgets.QPushButton(iOSInternationalTest)
        self.but_cancel.setGeometry(QtCore.QRect(370, 380, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.but_cancel.setFont(font)
        self.but_cancel.setObjectName("but_cancel")

        self.retranslateUi(iOSInternationalTest)
        QtCore.QMetaObject.connectSlotsByName(iOSInternationalTest)

    def retranslateUi(self, iOSInternationalTest):
        _translate = QtCore.QCoreApplication.translate
        iOSInternationalTest.setWindowTitle(_translate("iOSInternationalTest", "iOS-国际化测试配制"))
        self.label.setText(_translate("iOSInternationalTest", "iOS国际化测试配制信息"))
        self.checkBox.setText(_translate("iOSInternationalTest", "波兰语"))
        self.checkBox_9.setText(_translate("iOSInternationalTest", "荷兰语"))
        self.checkBox_5.setText(_translate("iOSInternationalTest", "西班牙"))
        self.checkBox_2.setText(_translate("iOSInternationalTest", "英文"))
        self.checkBox_3.setText(_translate("iOSInternationalTest", "德语"))
        self.checkBox_4.setText(_translate("iOSInternationalTest", "法语"))
        self.checkBox_7.setText(_translate("iOSInternationalTest", "意大利语"))
        self.checkBox_8.setText(_translate("iOSInternationalTest", "日语"))
        self.checkBox_10.setText(_translate("iOSInternationalTest", "俄语"))
        self.checkBox_6.setText(_translate("iOSInternationalTest", "葡萄牙语"))
        self.label_2.setText(_translate("iOSInternationalTest", "IOS代码路径："))
        self.label_3.setText(_translate("iOSInternationalTest", "测试输出结果路径："))
        self.pushButton.setText(_translate("iOSInternationalTest", "浏览"))
        self.pushButton_2.setText(_translate("iOSInternationalTest", "浏览"))
        self.label_4.setText(_translate("iOSInternationalTest", "选择测试语言："))
        self.but_sure.setText(_translate("iOSInternationalTest", "开始执行"))
        self.but_cancel.setText(_translate("iOSInternationalTest", "取 消"))
