# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestTools(object):
    def setupUi(self, TestTools):
        TestTools.setObjectName("TestTools")
        TestTools.resize(952, 679)
        TestTools.setFixedSize(952, 679)
        self.centralwidget = QtWidgets.QWidget(TestTools)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 0, 821, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 200, 941, 431))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 921, 401))
        self.textEdit.setObjectName("textEdit")
        TestTools.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestTools)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        TestTools.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestTools)
        self.statusbar.setObjectName("statusbar")
        TestTools.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(TestTools)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(TestTools)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(TestTools)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(TestTools)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuite = QtWidgets.QAction(TestTools)
        self.actionQuite.setCheckable(False)
        self.actionQuite.setShortcut("Ctrl+Q")
        self.actionQuite.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionQuite.setObjectName("actionQuite")
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuite)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(TestTools)
        QtCore.QMetaObject.connectSlotsByName(TestTools)

    def retranslateUi(self, TestTools):
        _translate = QtCore.QCoreApplication.translate
        TestTools.setWindowTitle(_translate("TestTools", "MainWindow"))
        self.pushButton.setText(_translate("TestTools", "iOS国际化测试"))
        self.pushButton_5.setText(_translate("TestTools", "Manifest.xml安全检查"))
        self.pushButton_8.setText(_translate("TestTools", "button8"))
        self.pushButton_2.setText(_translate("TestTools", "iOS资源文件重复值检查"))
        self.pushButton_3.setText(_translate("TestTools", "iOS国际化替换"))
        self.pushButton_6.setText(_translate("TestTools", "Button6"))
        self.pushButton_9.setText(_translate("TestTools", "禅道Bug超期检查"))
        self.pushButton_4.setText(_translate("TestTools", "Android_Monkey压力测试"))
        self.pushButton_7.setText(_translate("TestTools", "Button7"))
        self.groupBox.setTitle(_translate("TestTools", "日志信息"))
        self.textEdit.setHtml(_translate("TestTools", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuAbout.setTitle(_translate("TestTools", "help"))
        self.menuFile.setTitle(_translate("TestTools", "File"))
        self.actionHelp.setText(_translate("TestTools", "Help"))
        self.actionAbout.setText(_translate("TestTools", "About"))
        self.actionNew.setText(_translate("TestTools", "New"))
        self.actionOpen.setText(_translate("TestTools", "Open"))
        self.actionQuite.setText(_translate("TestTools", "Quite"))

