# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonkeyView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonkeyView(object):
    def setupUi(self, MonkeyView):
        MonkeyView.setObjectName("MonkeyView")
        MonkeyView.resize(591, 514)
        self.label = QtWidgets.QLabel(MonkeyView)
        self.label.setGeometry(QtCore.QRect(20, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 331, 31))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(MonkeyView)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 130, 331, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(MonkeyView)
        self.pushButton.setGeometry(QtCore.QRect(450, 130, 75, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(MonkeyView)
        self.listWidget.setGeometry(QtCore.QRect(15, 200, 561, 151))
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 210, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_2 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 250, 111, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 250, 61, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_3 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 290, 61, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.checkBox_4 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 330, 131, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 330, 61, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox_5 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_5.setGeometry(QtCore.QRect(290, 210, 151, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_7.setGeometry(QtCore.QRect(440, 210, 61, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.checkBox_6 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_6.setGeometry(QtCore.QRect(290, 250, 151, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_8.setGeometry(QtCore.QRect(440, 250, 61, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.checkBox_7 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_7.setGeometry(QtCore.QRect(290, 290, 151, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_9.setGeometry(QtCore.QRect(440, 290, 61, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.checkBox_8 = QtWidgets.QCheckBox(MonkeyView)
        self.checkBox_8.setGeometry(QtCore.QRect(290, 330, 151, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_10.setGeometry(QtCore.QRect(440, 330, 61, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_3 = QtWidgets.QLabel(MonkeyView)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 361, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(MonkeyView)
        self.label_4.setGeometry(QtCore.QRect(10, 370, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(MonkeyView)
        self.label_5.setGeometry(QtCore.QRect(20, 400, 101, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 400, 81, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_6 = QtWidgets.QLabel(MonkeyView)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(MonkeyView)
        self.label_7.setGeometry(QtCore.QRect(180, 20, 201, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(MonkeyView)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 450, 191, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MonkeyView)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 20, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(MonkeyView)
        self.label_8.setGeometry(QtCore.QRect(240, 400, 61, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_12 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_12.setGeometry(QtCore.QRect(300, 400, 101, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(MonkeyView)
        self.lineEdit_13.setGeometry(QtCore.QRect(460, 400, 101, 21))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_9 = QtWidgets.QLabel(MonkeyView)
        self.label_9.setGeometry(QtCore.QRect(420, 400, 61, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(MonkeyView)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 450, 191, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(MonkeyView)
        QtCore.QMetaObject.connectSlotsByName(MonkeyView)

    def retranslateUi(self, MonkeyView):
        _translate = QtCore.QCoreApplication.translate
        MonkeyView.setWindowTitle(_translate("MonkeyView", "Dialog"))
        self.label.setText(_translate("MonkeyView", "APK包名："))
        self.lineEdit.setText(_translate("MonkeyView", "com.huawei.solarsafe"))
        self.label_2.setText(_translate("MonkeyView", "存放结果："))
        self.pushButton.setText(_translate("MonkeyView", "浏览"))
        self.checkBox.setText(_translate("MonkeyView", "触摸事件百分比%"))
        self.checkBox_2.setText(_translate("MonkeyView", "运动事件百分比%"))
        self.checkBox_3.setText(_translate("MonkeyView", "轨迹球事件百分比%"))
        self.checkBox_4.setText(_translate("MonkeyView", "系统导航（%）"))
        self.checkBox_5.setText(_translate("MonkeyView", "基础导航（%）"))
        self.checkBox_6.setText(_translate("MonkeyView", "主导航事件%"))
        self.checkBox_7.setText(_translate("MonkeyView", "启动Activity事件（%）"))
        self.checkBox_8.setText(_translate("MonkeyView", "其它事件%"))
        self.label_3.setText(_translate("MonkeyView", "事件选择（所有事件相加为100%，不可超过）"))
        self.label_4.setText(_translate("MonkeyView", "其它设置"))
        self.label_5.setText(_translate("MonkeyView", "事件等待时间（ms）"))
        self.label_6.setText(_translate("MonkeyView", "可测试设备"))
        self.label_7.setText(_translate("MonkeyView", "显示可测试设备串号"))
        self.pushButton_2.setText(_translate("MonkeyView", "开始Monkey"))
        self.pushButton_3.setText(_translate("MonkeyView", "手到检测"))
        self.label_8.setText(_translate("MonkeyView", "事件次数："))
        self.label_9.setText(_translate("MonkeyView", "随机值："))
        self.pushButton_4.setText(_translate("MonkeyView", "终止测试"))
